
zuul:
  routes:
    member:
      path: /members/**
    book:
      path: /books/**

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
  contextPath: /api/v1