eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: book-server
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://postgres-book:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"

server:
  port: 8080

# Only the gateway should create a session.
security:
  sessions: NEVER

